[package]
name = "question_016"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.big_nums]
path = "../utils/big_nums"
